site_name: dumpgps
site_description: dump gps info from photos
site_author: Ken Lai
repo_url: https://github.com/KenMercusLai/dumpgps

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
